package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoGrouponRules;
import com.luomor.coco.db.domain.CocoGrouponRulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(CocoGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(CocoGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int insert(CocoGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(CocoGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    CocoGrouponRules selectOneByExample(CocoGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    CocoGrouponRules selectOneByExampleSelective(@Param("example") CocoGrouponRulesExample example, @Param("selective") CocoGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    List<CocoGrouponRules> selectByExampleSelective(@Param("example") CocoGrouponRulesExample example, @Param("selective") CocoGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    List<CocoGrouponRules> selectByExample(CocoGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    CocoGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    CocoGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    CocoGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoGrouponRules record, @Param("example") CocoGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoGrouponRules record, @Param("example") CocoGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}