package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoFeedback;
import com.luomor.coco.db.domain.CocoFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    long countByExample(CocoFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(CocoFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int insert(CocoFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int insertSelective(CocoFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    CocoFeedback selectOneByExample(CocoFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    CocoFeedback selectOneByExampleSelective(@Param("example") CocoFeedbackExample example, @Param("selective") CocoFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    List<CocoFeedback> selectByExampleSelective(@Param("example") CocoFeedbackExample example, @Param("selective") CocoFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    List<CocoFeedback> selectByExample(CocoFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    CocoFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    CocoFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    CocoFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoFeedback record, @Param("example") CocoFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoFeedback record, @Param("example") CocoFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}