package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoGoodsSpecification;
import com.luomor.coco.db.domain.CocoGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(CocoGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(CocoGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int insert(CocoGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(CocoGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    CocoGoodsSpecification selectOneByExample(CocoGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    CocoGoodsSpecification selectOneByExampleSelective(@Param("example") CocoGoodsSpecificationExample example, @Param("selective") CocoGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    List<CocoGoodsSpecification> selectByExampleSelective(@Param("example") CocoGoodsSpecificationExample example, @Param("selective") CocoGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    List<CocoGoodsSpecification> selectByExample(CocoGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    CocoGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    CocoGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    CocoGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoGoodsSpecification record, @Param("example") CocoGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoGoodsSpecification record, @Param("example") CocoGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}