package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoNoticeAdmin;
import com.luomor.coco.db.domain.CocoNoticeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(CocoNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(CocoNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int insert(CocoNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(CocoNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    CocoNoticeAdmin selectOneByExample(CocoNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    CocoNoticeAdmin selectOneByExampleSelective(@Param("example") CocoNoticeAdminExample example, @Param("selective") CocoNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    List<CocoNoticeAdmin> selectByExampleSelective(@Param("example") CocoNoticeAdminExample example, @Param("selective") CocoNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    List<CocoNoticeAdmin> selectByExample(CocoNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    CocoNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    CocoNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    CocoNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoNoticeAdmin record, @Param("example") CocoNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoNoticeAdmin record, @Param("example") CocoNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}