package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoCollect;
import com.luomor.coco.db.domain.CocoCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    long countByExample(CocoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int deleteByExample(CocoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int insert(CocoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int insertSelective(CocoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    CocoCollect selectOneByExample(CocoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    CocoCollect selectOneByExampleSelective(@Param("example") CocoCollectExample example, @Param("selective") CocoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    List<CocoCollect> selectByExampleSelective(@Param("example") CocoCollectExample example, @Param("selective") CocoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    List<CocoCollect> selectByExample(CocoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    CocoCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    CocoCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    CocoCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoCollect record, @Param("example") CocoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoCollect record, @Param("example") CocoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}