package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoGroupon;
import com.luomor.coco.db.domain.CocoGrouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    long countByExample(CocoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(CocoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int insert(CocoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int insertSelective(CocoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    CocoGroupon selectOneByExample(CocoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    CocoGroupon selectOneByExampleSelective(@Param("example") CocoGrouponExample example, @Param("selective") CocoGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    List<CocoGroupon> selectByExampleSelective(@Param("example") CocoGrouponExample example, @Param("selective") CocoGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    List<CocoGroupon> selectByExample(CocoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    CocoGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    CocoGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    CocoGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoGroupon record, @Param("example") CocoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoGroupon record, @Param("example") CocoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}