package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoRegion;
import com.luomor.coco.db.domain.CocoRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    long countByExample(CocoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int deleteByExample(CocoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int insert(CocoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int insertSelective(CocoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    CocoRegion selectOneByExample(CocoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    CocoRegion selectOneByExampleSelective(@Param("example") CocoRegionExample example, @Param("selective") CocoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    List<CocoRegion> selectByExampleSelective(@Param("example") CocoRegionExample example, @Param("selective") CocoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    List<CocoRegion> selectByExample(CocoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    CocoRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    CocoRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoRegion record, @Param("example") CocoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoRegion record, @Param("example") CocoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoRegion record);
}