package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoUser;
import com.luomor.coco.db.domain.CocoUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    long countByExample(CocoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int deleteByExample(CocoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int insert(CocoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int insertSelective(CocoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    CocoUser selectOneByExample(CocoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    CocoUser selectOneByExampleSelective(@Param("example") CocoUserExample example, @Param("selective") CocoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    List<CocoUser> selectByExampleSelective(@Param("example") CocoUserExample example, @Param("selective") CocoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    List<CocoUser> selectByExample(CocoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    CocoUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    CocoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    CocoUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoUser record, @Param("example") CocoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoUser record, @Param("example") CocoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}