package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoAftersale;
import com.luomor.coco.db.domain.CocoAftersaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    long countByExample(CocoAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(CocoAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int insert(CocoAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(CocoAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    CocoAftersale selectOneByExample(CocoAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    CocoAftersale selectOneByExampleSelective(@Param("example") CocoAftersaleExample example, @Param("selective") CocoAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    List<CocoAftersale> selectByExampleSelective(@Param("example") CocoAftersaleExample example, @Param("selective") CocoAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    List<CocoAftersale> selectByExample(CocoAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    CocoAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    CocoAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    CocoAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoAftersale record, @Param("example") CocoAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoAftersale record, @Param("example") CocoAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}