package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoCart;
import com.luomor.coco.db.domain.CocoCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    long countByExample(CocoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int deleteByExample(CocoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int insert(CocoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int insertSelective(CocoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    CocoCart selectOneByExample(CocoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    CocoCart selectOneByExampleSelective(@Param("example") CocoCartExample example, @Param("selective") CocoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    List<CocoCart> selectByExampleSelective(@Param("example") CocoCartExample example, @Param("selective") CocoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    List<CocoCart> selectByExample(CocoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    CocoCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    CocoCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    CocoCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoCart record, @Param("example") CocoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoCart record, @Param("example") CocoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}