package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoComment;
import com.luomor.coco.db.domain.CocoCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    long countByExample(CocoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int deleteByExample(CocoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int insert(CocoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int insertSelective(CocoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    CocoComment selectOneByExample(CocoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    CocoComment selectOneByExampleSelective(@Param("example") CocoCommentExample example, @Param("selective") CocoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    List<CocoComment> selectByExampleSelective(@Param("example") CocoCommentExample example, @Param("selective") CocoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    List<CocoComment> selectByExample(CocoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    CocoComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    CocoComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    CocoComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoComment record, @Param("example") CocoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoComment record, @Param("example") CocoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}