package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoSearchHistory;
import com.luomor.coco.db.domain.CocoSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    long countByExample(CocoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(CocoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int insert(CocoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int insertSelective(CocoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    CocoSearchHistory selectOneByExample(CocoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    CocoSearchHistory selectOneByExampleSelective(@Param("example") CocoSearchHistoryExample example, @Param("selective") CocoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    List<CocoSearchHistory> selectByExampleSelective(@Param("example") CocoSearchHistoryExample example, @Param("selective") CocoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    List<CocoSearchHistory> selectByExample(CocoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    CocoSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    CocoSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    CocoSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoSearchHistory record, @Param("example") CocoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoSearchHistory record, @Param("example") CocoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}