package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoStorage;
import com.luomor.coco.db.domain.CocoStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    long countByExample(CocoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int deleteByExample(CocoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int insert(CocoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int insertSelective(CocoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    CocoStorage selectOneByExample(CocoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    CocoStorage selectOneByExampleSelective(@Param("example") CocoStorageExample example, @Param("selective") CocoStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    List<CocoStorage> selectByExampleSelective(@Param("example") CocoStorageExample example, @Param("selective") CocoStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    List<CocoStorage> selectByExample(CocoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    CocoStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    CocoStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    CocoStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoStorage record, @Param("example") CocoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoStorage record, @Param("example") CocoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}