package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoGoodsAttribute;
import com.luomor.coco.db.domain.CocoGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(CocoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(CocoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int insert(CocoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(CocoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    CocoGoodsAttribute selectOneByExample(CocoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    CocoGoodsAttribute selectOneByExampleSelective(@Param("example") CocoGoodsAttributeExample example, @Param("selective") CocoGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    List<CocoGoodsAttribute> selectByExampleSelective(@Param("example") CocoGoodsAttributeExample example, @Param("selective") CocoGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    List<CocoGoodsAttribute> selectByExample(CocoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    CocoGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    CocoGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    CocoGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoGoodsAttribute record, @Param("example") CocoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoGoodsAttribute record, @Param("example") CocoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}