package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoGoods;
import com.luomor.coco.db.domain.CocoGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    long countByExample(CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int deleteByExample(CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int insert(CocoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int insertSelective(CocoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    CocoGoods selectOneByExample(CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    CocoGoods selectOneByExampleSelective(@Param("example") CocoGoodsExample example, @Param("selective") CocoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    CocoGoods selectOneByExampleWithBLOBs(CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    List<CocoGoods> selectByExampleSelective(@Param("example") CocoGoodsExample example, @Param("selective") CocoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    List<CocoGoods> selectByExampleWithBLOBs(CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    List<CocoGoods> selectByExample(CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    CocoGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    CocoGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    CocoGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoGoods record, @Param("example") CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CocoGoods record, @Param("example") CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoGoods record, @Param("example") CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CocoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}