package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoOrderGoods;
import com.luomor.coco.db.domain.CocoOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    long countByExample(CocoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(CocoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int insert(CocoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(CocoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    CocoOrderGoods selectOneByExample(CocoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    CocoOrderGoods selectOneByExampleSelective(@Param("example") CocoOrderGoodsExample example, @Param("selective") CocoOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    List<CocoOrderGoods> selectByExampleSelective(@Param("example") CocoOrderGoodsExample example, @Param("selective") CocoOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    List<CocoOrderGoods> selectByExample(CocoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    CocoOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    CocoOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    CocoOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoOrderGoods record, @Param("example") CocoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoOrderGoods record, @Param("example") CocoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}