package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoAdmin;
import com.luomor.coco.db.domain.CocoAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    long countByExample(CocoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int deleteByExample(CocoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int insert(CocoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int insertSelective(CocoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    CocoAdmin selectOneByExample(CocoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    CocoAdmin selectOneByExampleSelective(@Param("example") CocoAdminExample example, @Param("selective") CocoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    List<CocoAdmin> selectByExampleSelective(@Param("example") CocoAdminExample example, @Param("selective") CocoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    List<CocoAdmin> selectByExample(CocoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    CocoAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    CocoAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    CocoAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoAdmin record, @Param("example") CocoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoAdmin record, @Param("example") CocoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}