package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoGoodsProduct;
import com.luomor.coco.db.domain.CocoGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    long countByExample(CocoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(CocoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int insert(CocoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(CocoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    CocoGoodsProduct selectOneByExample(CocoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    CocoGoodsProduct selectOneByExampleSelective(@Param("example") CocoGoodsProductExample example, @Param("selective") CocoGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    List<CocoGoodsProduct> selectByExampleSelective(@Param("example") CocoGoodsProductExample example, @Param("selective") CocoGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    List<CocoGoodsProduct> selectByExample(CocoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    CocoGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    CocoGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    CocoGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoGoodsProduct record, @Param("example") CocoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoGoodsProduct record, @Param("example") CocoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}