package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoPermission;
import com.luomor.coco.db.domain.CocoPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    long countByExample(CocoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int deleteByExample(CocoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int insert(CocoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int insertSelective(CocoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    CocoPermission selectOneByExample(CocoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    CocoPermission selectOneByExampleSelective(@Param("example") CocoPermissionExample example, @Param("selective") CocoPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    List<CocoPermission> selectByExampleSelective(@Param("example") CocoPermissionExample example, @Param("selective") CocoPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    List<CocoPermission> selectByExample(CocoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    CocoPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    CocoPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    CocoPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoPermission record, @Param("example") CocoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoPermission record, @Param("example") CocoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}