package com.luomor.coco.db.dao;

import com.luomor.coco.db.domain.CocoSystem;
import com.luomor.coco.db.domain.CocoSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CocoSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    long countByExample(CocoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int deleteByExample(CocoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int insert(CocoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int insertSelective(CocoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    CocoSystem selectOneByExample(CocoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    CocoSystem selectOneByExampleSelective(@Param("example") CocoSystemExample example, @Param("selective") CocoSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    List<CocoSystem> selectByExampleSelective(@Param("example") CocoSystemExample example, @Param("selective") CocoSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    List<CocoSystem> selectByExample(CocoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    CocoSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CocoSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    CocoSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    CocoSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CocoSystem record, @Param("example") CocoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CocoSystem record, @Param("example") CocoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CocoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CocoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CocoSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coco_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}